<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\HephaestusWorkbench.Core\HephaestusWorkbench.Core.csproj" />
    <ProjectReference Include="..\HephaestusWorkbench.Data\HephaestusWorkbench.Data.csproj" />
    <ProjectReference Include="..\HephaestusWorkbench.PluginSDK\HephaestusWorkbench.PluginSDK.csproj" />
    <PackageReference Include="NSec.Cryptography" Version="22.4.0" />
    <PackageReference Include="SSH.NET" Version="2026.0.0" />
  </ItemGroup>
</Project>
